rootProject.name = 'remarketing-system'

include 'common-proto'
include 'common-core'
include 'common-security'
include 'auth-service'
include 'product-catalog'
include 'order-cart'
include 'user-behavior'
include 'campaign-management'
include 'recommendation-engine'
include 'remarketing-execution'
include 'ab-testing'
include 'analytics-insights'
include 'application'
include 'fraud-detection'
