syntax = "proto3";

package com.remarketing.auth;

option java_multiple_files = true;
option java_package = "com.remarketing.auth.grpc";
option java_outer_classname = "AuthProto";

service AuthService {
    rpc Register (RegisterRequest) returns (RegisterResponse);
    rpc Login (LoginRequest) returns (LoginResponse);
    rpc Logout (LogoutRequest) returns (LogoutResponse);
    rpc DeleteAccount (DeleteAccountRequest) returns (DeleteAccountResponse);
}

message RegisterRequest {
    string username = 1;
    string password = 2;
    string email = 3;
    string role = 4;
}

message RegisterResponse {
    string user_id = 1;
    string message = 2;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    string token = 1;
    string message = 2;
    string role = 3;
}

message LogoutRequest {
    string token = 1;
}

message LogoutResponse {
    bool success = 1;
    string message = 2;
}

message DeleteAccountRequest {
    string user_id = 1;
}

message DeleteAccountResponse {
    bool success = 1;
    string message = 2;
}
