syntax = "proto3";

package com.remarketing.execution;

option java_multiple_files = true;
option java_package = "com.remarketing.execution.grpc";
option java_outer_classname = "ExecutionProto";

service ExecutionService {
    rpc ExecuteCampaign (ExecuteCampaignRequest) returns (ExecuteCampaignResponse);
}

message ExecuteCampaignRequest {
    string campaign_id = 1;
    string user_id = 2;
    string notification_type = 3; // EMAIL or PUSH
    string message = 4;
}

message ExecuteCampaignResponse {
    bool success = 1;
    string status_message = 2;
}
